version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - '5000:5000'    

  view:
    build: 
      context: .
      dockerfile: view.dockerfile
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - view
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  # database:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGODB_USER: "${MONGO_USER}"
  #     MONGODB_DATABASE: "${MONGO_DB}"
  #     MONGODB_PASS: "${MONGO_DB}"
  #   volumes:
  #     - ../mongo:/data/db

networks: 
  default:
    name: devops_network