version: "3.7"

services:
  view:
    build: 
      context: .
      dockerfile: view-app.dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ../view:/app

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - view
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks: 
  default:
    name: devops_network